### ISSUE TITLE
hex stratum conf file

### ISSUE THREAD

**Issue by goodthebest** [XDNA-Core/Yiimp-HEX#2]
Hi @XDNA-Core 

Which file can be used for HEX from /stratum sample configs? I do not for any hex algo file?

**Comment by XDNA-Core** [comment]
You can create new file and use something like this
[TCP]
server = 
port = 5100
password = 

[SQL]
host = localhost
database = yiimpfrontend
username = stratum
password = 

[STRATUM]
algo = hex
difficulty = 8
max_ttf = 5000
